### PR TITLE
Clicking on a color now copies RGB code

### LINKED ISSUE #2: Allow rgb() codes to be copied onClick
Need to set the rgb() codes in the palette swatches as links that can be clicked so that the code is copied to clipboard.

### PR DESCRIPTION
**Pull request by plin0009**
Fixes #2 : when a column is clicked, a string like `rgb(99, 33, 234)` is copied to the clipboard.

I see that #6 plans to move the columns to HTML. When generating the colors, the `onclick` attribute of the element should be updated in the `generate` function. 

I hope my changes helped!

### CODE REVIEW

**Comment by r0b0-s1av3** [comment]
@plin0009 Thanks! I'll merge these changes once we've updated the codebase with the [other pull request (#6)](https://github.com/r0b0-s1av3/color-generator/issues/6) we're working on. It'll have to be updated slightly to have your `copy()` function get the text that was selected by the user since we will have three options.

If I need to make updates, I can commit to your branch and then I'll get your pull request integrated.

Thanks for the help!

**Comment by thekanbo** [comment]
@plin0009 It may be a good idea to update these to use an `each()` function and an event listener in the JS files, rather than using an `onClick` method on the element itself, especially now that there are three different color codes for each column.

**Comment by r0b0-s1av3** [comment]
@thekanbo Looks like we had the same idea here. I resolved the conflicts by taking the solution by @plin0009 and turning it into three `.click()` handlers that call his `copy()` function.

**Comment by plin0009** [comment]
Awesome! I love how it's coming together

**Pull request merged**
